jobs:
# Mac and Linux use the same template with different matrixes
- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: macOS
    vmImage: macos-13
    matrix:
      py310:
        PYTHON: '3.10'
        CONDA_ENV: cienv
        MACOSX_DEPLOYMENT_TARGET: '11.0'
      py311:
        PYTHON: '3.11'
        CONDA_ENV: cienv
        MACOSX_DEPLOYMENT_TARGET: '11.0'
      py312:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        MACOSX_DEPLOYMENT_TARGET: '11.0'
      py313:
        PYTHON: '3.13'
        CONDA_ENV: cienv
        MACOSX_DEPLOYMENT_TARGET: '11.0'

      llvm16:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        LLVM: '16'
        MACOSX_DEPLOYMENT_TARGET: '11.0'

      opaque_pointers:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        OPAQUE_POINTERS: yes
        MACOSX_DEPLOYMENT_TARGET: '11.0'

- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: Linux
    vmImage: ubuntu-20.04
    matrix:
      py310:
        PYTHON: '3.10'
        CONDA_ENV: cienv
        RUN_FLAKE8: yes
      py311:
        PYTHON: '3.11'
        CONDA_ENV: cienv
        RUN_FLAKE8: yes
        RUN_CLANG_FORMAT: yes
      py312:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        RUN_FLAKE8: yes
        RUN_CLANG_FORMAT: yes
      py313:
        PYTHON: '3.13'
        CONDA_ENV: cienv
        RUN_FLAKE8: yes
        RUN_CLANG_FORMAT: yes
# temporarily disabled
#       pypy:
#         PYTHON: pypy
#         CONDA_ENV: cienv
      py310_wheel:
        PYTHON: '3.10'
        CONDA_ENV: cienv
        WHEEL: 'yes'
      py311_wheel:
        PYTHON: '3.11'
        CONDA_ENV: cienv
        WHEEL: 'yes'
      py312_wheel:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        WHEEL: 'yes'
      py313_wheel:
        PYTHON: '3.13'
        CONDA_ENV: cienv
        WHEEL: 'yes'

      llvm16:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        LLVM: '16'

      opaque_pointers:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        OPAQUE_POINTERS: yes

- template: buildscripts/azure/azure-windows.yml
  parameters:
    name: Windows
    vmImage: windows-2019

- job: check_formatting
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      set -e
      sudo apt install -y clang-format
      clang-format -n -Werror ffi/*.cpp ffi/*.h
    displayName: Check C++ formatting
